server:
  port: 8080
  servlet:
    context-path: /api

spring:
  data:
    mongodb:
      database: crud_api_todo
      port: 27017
      host: localhost
  application:
    name: mongodb-crud
  jpa:
    show-sql: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

logging:
  level:
    root: warn
    com.melardev: debug
    org.springframework.web: info